const state = { items: [], query: '', category: 'all', sort: 'recommended', page: 1, perPage: 6 };
const $ = (selector) => document.querySelector(selector);
const grid = $('#catalog-grid');
const money = (value) => value == null ? 'Consulte' : value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL', minimumFractionDigits: 0 });
const text = (value) => value == null || value === '' ? '' : String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const weight = (option) => Number.isFinite(Number(option.weight)) ? Number(option.weight) : null;
const priceTiers = [{ label: 'Até 50 un.', rate: 375 }, { label: '51 a 100 un.', rate: 325 }, { label: 'Mais de 100 un.', rate: 275 }];
const priceForTier = (option, rate) => { const grams = weight(option); return grams == null ? null : Math.ceil((grams * rate / 100) / 5) * 5; };
const copy = { Organização: 'Mais ordem e leveza para a sua rotina.', Casa: 'Um detalhe especial para deixar seu espaço mais bonito.', Presentes: 'Um presente criativo, útil e cheio de personalidade.', Diversão: 'Uma peça divertida para brincar, relaxar e colecionar.', Escritório: 'Mais praticidade e personalidade para a sua mesa.', Acessórios: 'Um detalhe funcional para acompanhar o seu dia.', Aviação: 'Uma peça marcante para quem ama design e aviação.', Embalagem: 'Uma apresentação especial para tornar cada entrega inesquecível.', Fidget: 'Uma pausa gostosa para as mãos e para a mente.', Utilitário: 'Uma solução inteligente para facilitar sua rotina.', 'Identidade visual': 'Uma peça exclusiva para destacar a sua marca.', 'Brinde inteligente / NFC': 'Um brinde memorável que aproxima sua marca das pessoas.' };
const localImages = { 'Porta-copos': './assets/images/porta-copos.png' };
function image(url, alt, fallbackUrl = '') { if (!url) return '<div class="image-fallback">Imagem<br>indisponível</div>'; const fallback = fallbackUrl && fallbackUrl !== url ? `this.onerror=function(){this.hidden=true;this.nextElementSibling.hidden=false};this.src='${text(fallbackUrl)}'` : 'this.hidden=true;this.nextElementSibling.hidden=false'; return `<img src="${text(url)}" alt="${text(alt)}" loading="lazy" onerror="${fallback}"><div class="image-fallback" hidden>Imagem indisponível</div>`; }
function productImage(item, option) { const local = localImages[item.name.trim()]; const candidate = option.imageUrl || item.reference; const candidateIsLocal = candidate && candidate.startsWith('assets/images/'); return { primary: local || candidate, fallback: local ? candidate : (candidateIsLocal ? item.reference : '') }; }
function optionScore(option) { return Number(option.score) || 0; }
function optionsFor(item) { return [...(item.options || [])].sort((a, b) => optionScore(b) - optionScore(a)); }
function visible() { const query = state.query.trim().toLowerCase(); return state.items.flatMap((item) => optionsFor(item).map((option, index) => ({ item, option, index }))).filter(({ item, option }) => (state.category === 'all' || item.category === state.category) && (!query || `${item.name} ${item.category} ${item.summary || ''} ${option.name} ${option.colors || ''}`.toLowerCase().includes(query))).sort((a, b) => { if (state.sort === 'name') return a.item.name.localeCompare(b.item.name, 'pt-BR') || a.option.name.localeCompare(b.option.name, 'pt-BR'); if (state.sort === 'price') return (priceForTier(a.option, 375) ?? Infinity) - (priceForTier(b.option, 375) ?? Infinity); return optionScore(b.option) - optionScore(a.option); }); }
function card(entry) { const { item, option, index } = entry; const description = copy[item.category] || 'Uma peça especial, feita para fazer parte da sua rotina.'; const imageSource = productImage(item, option); const tierPrices = priceTiers.map((tier) => `<div class="tier-price"><span>${tier.label}</span><strong>${money(priceForTier(option, tier.rate))}</strong><small>por peça</small></div>`).join(''); return `<article class="product-card"><div class="product-image">${image(imageSource.primary, `${item.name} — ${option.name}`, imageSource.fallback)}<span class="product-tag">${text(item.category)}</span></div><div class="product-info"><span class="product-variant">Opção ${index + 1}</span><h3>${text(item.name)}</h3><p class="variant-name">${text(option.name)}</p><span class="product-category">${description}</span><div class="tier-prices" aria-label="Preços por quantidade">${tierPrices}</div><button class="quote-button" type="button" data-product="${text(item.name)} — ${text(option.name)}">Quero esse</button></div></article>`; }
function render() { const entries = visible(); const totalPages = Math.max(1, Math.ceil(entries.length / state.perPage)); state.page = Math.min(state.page, totalPages); const start = (state.page - 1) * state.perPage; grid.innerHTML = entries.slice(start, start + state.perPage).map(card).join(''); $('#empty-state').hidden = entries.length > 0; renderPagination(entries.length, totalPages); document.querySelectorAll('.quote-button').forEach((button) => button.addEventListener('click', () => { const product = button.dataset.product; window.location.href = `mailto:?subject=${encodeURIComponent(`Cotação: ${product}`)}&body=${encodeURIComponent(`Olá! Tenho interesse em ${product}. Gostaria de confirmar cores, disponibilidade e entrega.`)}`; })); }
function renderPagination(total, totalPages) { const pagination = $('#pagination'); if (total <= state.perPage) { pagination.innerHTML = ''; return; } pagination.innerHTML = `<button class="page-button" type="button" data-page="prev" ${state.page === 1 ? 'disabled' : ''} aria-label="Página anterior">←</button>${Array.from({ length: totalPages }, (_, index) => `<button class="page-button${state.page === index + 1 ? ' active' : ''}" type="button" data-page="${index + 1}" aria-current="${state.page === index + 1 ? 'page' : 'false'}">${index + 1}</button>`).join('')}<button class="page-button" type="button" data-page="next" ${state.page === totalPages ? 'disabled' : ''} aria-label="Próxima página">→</button>`; pagination.querySelectorAll('.page-button').forEach((button) => button.addEventListener('click', () => { const target = button.dataset.page; state.page = target === 'prev' ? state.page - 1 : target === 'next' ? state.page + 1 : Number(target); render(); $('#catalogo').scrollIntoView({ behavior: 'smooth', block: 'start' }); })); }
async function init() { try { const response = await fetch('./data/models.json'); if (!response.ok) throw new Error(`HTTP ${response.status}`); state.items = await response.json(); const categories = [...new Set(state.items.map((item) => item.category).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'pt-BR')); $('#category-filters').innerHTML = '<button class="pill active" data-category="all">Tudo</button>' + categories.map((category) => `<button class="pill" data-category="${text(category)}">${text(category)}</button>`).join(''); document.querySelectorAll('.pill').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.pill').forEach((pill) => pill.classList.remove('active')); button.classList.add('active'); state.category = button.dataset.category; state.page = 1; render(); })); $('#search').addEventListener('input', (event) => { state.query = event.target.value; state.page = 1; render(); }); $('#sort').addEventListener('change', (event) => { state.sort = event.target.value; state.page = 1; render(); }); render(); } catch (error) { grid.innerHTML = '<p class="empty-state">Não foi possível carregar as peças.</p>'; console.error('[v0] Erro ao carregar catálogo:', error); } }
init();
