FROM nginx:1.27-alpine

COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY admin.html /usr/share/nginx/html/admin.html
COPY robots.txt /usr/share/nginx/html/robots.txt
COPY css /usr/share/nginx/html/css
COPY js /usr/share/nginx/html/js
COPY shared /usr/share/nginx/html/shared
COPY data /usr/share/nginx/html/data
COPY assets /usr/share/nginx/html/assets

EXPOSE 3000
